Repository ynput/ayon-backend, pull requests merged in 2023-01, with the labels that each got.

#7 More common models
  ayon_server/settings/__init__.py
  ayon_server/settings/models.py
Labels: enhancement

#10 Common settings models: Fix name of attribute from 'macos' to 'darwin'
  ayon_server/settings/models.py
Labels: bug

#8 Addons distribution: Change type and content of client zip file
  ayon_server/addons/addon.py
Labels: enhancement

#9 documentation: Add `ARCHITECTURE.md` document.
  ARCHITECTURE.md
Labels: documentation

#12 Settings: Add default imageio models for hosts
  ayon_server/settings/__init__.py
  ayon_server/settings/models.py
Labels: enhancement
