Repository ynput/ayon-backend, pull requests merged in 2024-10, with the labels that each got.

#328 Add unrealuasset as the publish template
  ayon_server/settings/anatomy/templates.py
Labels: type: enhancement

#371 GraphQL: Add priority field to Kanban node
  ayon_server/graphql/nodes/kanban.py
  ayon_server/graphql/resolvers/kanban.py
Labels: type: enhancement

#374 Functions for file uploads
  ayon_server/files/project_storage.py
  ayon_server/files/s3.py
  ayon_server/helpers/hierarchy_cache.py
  ayon_server/lib/postgres.py
  ayon_server/utils.py
Labels: type: maintenance

#376 Addons: server addon auto-update
  api/addons/install.py
  api/bundles/migration.py
  ayon_server/background/auto_update.py
  ayon_server/background/workers.py
  ayon_server/helpers/download_addon.py
  ayon_server/helpers/get_downloaded_addons.py
  ayon_server/helpers/migrate_addon_settings.py
  setup/initial_bundle.py
Labels: type: feature

#377 Database: allow importing files with unknown author
  api/users/users.py
  schemas/schema.project.sql
  schemas/schema.public.update.sql
Labels: type: enhancement

#381 Project files: Trashing project files directories upon deletion
  api/projects/projects.py
  ayon_server/files/project_storage.py
  ayon_server/helpers/download.py
  ayon_server/helpers/project_list.py
Labels: type: feature

#387 Webactions: Add option to abort action with reason
  api/actions/actions.py
Labels: type: enhancement

#393 Project: added missing event triggering
  api/projects/projects.py
Labels: type: bug

#394 Projects: speed up project deployment
  ayon_server/helpers/deploy_project.py
Labels: type: enhancement

#395 Skip inactive-projects clean-up
  ayon_server/background/clean_up.py
Labels: type: maintenance

#398 Watching and inbox rules improvements
  ayon_server/activities/event_hook.py
  ayon_server/activities/watchers/set_watchers.py
  ayon_server/graphql/resolvers/inbox.py
  schemas/schema.public.sql
Labels: type: enhancement

#401 Fix attribute model for enums
  ayon_server/entities/models/generator.py
Labels: type: bug

#402 Handle empty response when returning cached 'nothing to do' from enroll
  api/events/enroll.py
Labels: type: bug

#404 /api/info performance improvements
  api/onboarding/release.py
  api/system/info.py
  api/system/sites.py
  ayon_server/utils.py
Labels: type: bug

#408 Added folder reference to task activities
  ayon_server/activities/references.py
Labels: type: enhancement

#410 fix: provide project timestamp to cdn resolver
  api/files/files.py
  ayon_server/files/project_storage.py
  ayon_server/helpers/cdn.py
Labels: type: bug

#415 Scoped statuses in the default anatomy preset
  ayon_server/settings/anatomy/__init__.py
  ayon_server/settings/anatomy/link_types.py
  ayon_server/settings/anatomy/statuses.py
  ayon_server/settings/anatomy/tags.py
Labels: type: enhancement
