Repository ynput/ayon-backend, pull requests merged in 2024-12, with the labels that each got.

#444 GraphQL: Additional thumbnail data to nodes
  ayon_server/graphql/nodes/common.py
  ayon_server/graphql/nodes/folder.py
  ayon_server/graphql/nodes/kanban.py
  ayon_server/graphql/nodes/project.py
  ayon_server/graphql/nodes/task.py
  ayon_server/graphql/nodes/version.py
  ayon_server/graphql/nodes/workfile.py
  ayon_server/graphql/resolvers/kanban.py
Labels: type: feature

#449 Auth: fixed session invalidation logic
  ayon_server/auth/session.py
  ayon_server/config/ayonconfig.py
Labels: type: bug

#452 Track server updates in the database
  schemas/schema.public.sql
  setup/__main__.py
Labels: type: feature

#454 Added missing event to task/assign endpoint
  api/tasks/tasks.py
  ayon_server/events/patch.py
Labels: type: bug

#457 Market: Access to older release bundles
  api/market/__init__.py
  api/market/addons.py
  api/market/common.py
  api/market/releases.py
  api/onboarding/__init__.py
  api/onboarding/onboarding.py
Labels: type: enhancement

#467 Files: Grabbing still frames from videos
  api/files/files.py
  ayon_server/helpers/preview.py
Labels: type: feature

#466 Add traits field to representation model
  ayon_server/entities/models/fields.py
Labels: type: enhancement

#471 Allow all users to update checkboxes in comments
  api/activities/activity.py
  ayon_server/activities/update_activity.py
Labels: type: enhancement, sponsored

#473 Traffic statistics
  api/addons/install.py
  ayon_server/api/files.py
  ayon_server/files/s3.py
  ayon_server/helpers/statistics.py
  ayon_server/metrics/__init__.py
  ayon_server/metrics/traffic.py
  maintenance/tasks/push_metrics.py
  schemas/schema.public.sql
Labels: type: feature
