Repository ynput/ayon-backend, pull requests merged in 2024-08, with the labels that each got.

#306 Access groups: clean up user access groups when an access group is deleted
  api/access_groups/access_groups.py
Labels: enhancement

#271 Use strict models for marketplace endpoints
  api/market/market.py
  api/market/models.py
Labels: enhancement

#315 GraphQL: return empty connection when no project is present in kanban query
  ayon_server/graphql/resolvers/kanban.py
Labels: bug

#305 Settings: Improved SettingsField
  ayon_server/settings/__init__.py
  ayon_server/settings/anatomy/__init__.py
  ayon_server/settings/anatomy/folder_types.py
  ayon_server/settings/anatomy/link_types.py
  ayon_server/settings/anatomy/roots.py
  ayon_server/settings/anatomy/statuses.py
  ayon_server/settings/anatomy/tags.py
  ayon_server/settings/anatomy/task_types.py
  ayon_server/settings/anatomy/templates.py
  ayon_server/settings/models.py
  ayon_server/settings/settings_field.py
Labels: enhancement

#316 Database connection optimizations
  ayon_server/config.py
  ayon_server/helpers/deploy_project.py
  ayon_server/lib/postgres.py
  ayon_server/metrics/system.py
Labels: enhancement

#319 Events: allow specifying source topics in list in enroll + batch event delete
  api/events/__init__.py
  api/events/enroll.py
  api/events/operations.py
  ayon_server/events/enroll.py
  ayon_server/sqlfilter.py
Labels: enhancement

#321 Setup: Default access groups
  setup/access_groups.py
Labels: enhancement

#323 GraphQL: Querying tasks in nested folders
  ayon_server/graphql/resolvers/tasks.py
Labels: enhancement

#311 Settings: copy project settings when promoting a bundle
  api/bundles/actions.py
Labels: enhancement

#131 Configurable event retention
  ayon_server/background/clean_up.py
  ayon_server/background/log_cleaner.py
  ayon_server/background/workers.py
  ayon_server/config.py
Labels: enhancement

#327 Allow QuickTime files as proxies
  api/files/files.py
  api/files/video.py
  ayon_server/helpers/ffprobe.py
Labels: enhancement

#329 Fix returned entity URIs for representation entity type
  api/uris/queries.py
Labels: bug

#326 Settings: Migrate settings based on bundle
  api/addons/project_settings.py
  api/addons/studio_settings.py
  api/bundles/bundles.py
  api/bundles/migration.py
Labels: feature
