Repository ynput/ayon-backend, pull requests merged in 2024-06, with the labels that each got.

#224 Activity Feed: comment auto suggestions
  api/activities/__init__.py
  api/activities/router.py
  api/activities/suggest.py
  ayon_server/suggestions/__init__.py
  ayon_server/suggestions/folder.py
  ayon_server/suggestions/models.py
  ayon_server/suggestions/task.py
  ayon_server/suggestions/version.py
Labels: feature

#226 Inbox: Websocket notification
  ayon_server/activities/create_activity.py
  ayon_server/api/messaging.py
  ayon_server/events/eventstream.py
Labels: feature

#228 Profile: update user sessions when frontend preferences change
  api/users/users.py
Labels: bug

#231 Fix: operations when canFail is set to true
  ayon_server/entities/core/base.py
  ayon_server/entities/folder.py
  ayon_server/entities/version.py
Labels: bug

#238 Disallow listing users from unassigned projects
  ayon_server/graphql/__init__.py
  ayon_server/graphql/resolvers/users.py
Labels: bug

#241 Fix: Inherited attributes
  ayon_server/helpers/inherited_attributes.py
Labels: bug

#242 REST: Entity IDs to URIs endpoint
  api/resolve/__init__.py
  api/uris/__init__.py
  api/uris/queries.py
  api/uris/router.py
  api/uris/uris.py
Labels: feature

#243 Exclude addon endpoints and auth headers from openapi
  ayon_server/api/dependencies.py
  ayon_server/api/metadata.py
  ayon_server/api/server.py
  ayon_server/config.py
Labels: maintenance

#246 GraphQL: Filter folder by assignees
  ayon_server/graphql/resolvers/folders.py
Labels: enhancement

#250 Add application and tools enumeration functions.
  ayon_server/settings/enum.py
Labels: enhancement

#254 Utils: handle non-existent paths in dict_remove_path
  .gitignore
  api/addons/common.py
  ayon_server/utils.py
  tests/test_ayon_server_utils.py
Labels: bug

#249 Server-side kanban resolver
  ayon_server/graphql/__init__.py
  ayon_server/graphql/connections.py
  ayon_server/graphql/edges.py
  ayon_server/graphql/nodes/kanban.py
  ayon_server/graphql/resolvers/kanban.py
  ayon_server/graphql/resolvers/users.py
Labels: feature

#255 System metrics refactor
  api/system/metrics.py
  ayon_server/background/metrics_collector.py
  ayon_server/config.py
  ayon_server/metrics/__init__.py
  ayon_server/metrics/system.py
Labels: maintenance

#257 Activity feed: notify clients when an activity is created, updated or deleted
  api/activities/activity.py
  ayon_server/activities/create_activity.py
  ayon_server/activities/delete_activity.py
  ayon_server/activities/update_activity.py
Labels: enhancement
