Repository ynput/ayon-backend, pull requests merged in 2024-09, with the labels that each got.

#332 Create initialBundle using setup template
  api/bundles/bundles.py
  setup/initial_bundle.py
Labels: feature

#334 Resolve: Do not resolve all folders when uri contains just the project name
  api/resolve/__init__.py
Labels: bug

#341 Use ayon_init for setup
  ayon_server/__init__.py
  ayon_server/background/log_collector.py
  ayon_server/entities/core/attrib.py
  ayon_server/initialize.py
  ayon_server/lib/redis.py
  setup/__main__.py
  setup/initial_bundle.py
Labels: bug

#340 Fix: handle missing majorBrand field in reviewables check
  ayon_server/helpers/ffprobe.py
Labels: bug

#344 Frontend index caching
  ayon_server/api/frontend.py
  ayon_server/api/server.py
Labels: enhancement

#317 Removed exports from ayon_server.api to prevent circular imports
  api/addons/router.py
  api/users/router.py
  ayon_server/api/__init__.py
  ayon_server/api/server.py
Labels: maintenance

#349 Activity feed: Reactions
  api/activities/__init__.py
  api/activities/activity.py
  api/activities/reactions.py
  ayon_server/graphql/nodes/activity.py
Labels: feature

#335 Types: add types to getAccessGroups endpoint
  api/access_groups/access_groups.py
Labels: type: maintenance

#355 fix: column reference "id" is ambiguous
  ayon_server/graphql/resolvers/representations.py
Labels: type: bug

#356 Auth: Infinite loop when accessing unassigned project
  ayon_server/api/dependencies.py
Labels: type: bug

#336 Unassign user from tasks upon deletion
  ayon_server/entities/user.py
Labels: type: enhancement

#307 Resolver: Handle malformed URIs and provide error messages
  api/resolve/__init__.py
  api/resolve/models.py
Labels: type: enhancement

#324 Support for S3 storage and CDN for project files
  api/activities/activity.py
  api/files/files.py
  api/review/upload.py
  ayon_server/background/clean_up.py
  ayon_server/config.py
  ayon_server/files/__init__.py
  ayon_server/files/project_storage.py
  ayon_server/files/s3.py
  ayon_server/helpers/cdn.py
  ayon_server/helpers/preview.py
  ayon_server/helpers/project_files.py
  pyproject.toml
Labels: type: feature

#363 Include action identifier in default description
  ayon_server/actions/execute.py
Labels: type: enhancement

#287 Anatomy: Entity type scoped statuses
  ayon_server/settings/anatomy/statuses.py
  ayon_server/settings/settings_field.py
Labels: type: feature

#357 inherit setting field scope in list_overrides
  ayon_server/settings/overrides.py
Labels: type: bug

#314 Attributes: enums with additional metadata
  ayon_server/entities/core/attrib.py
  ayon_server/entities/models/generator.py
  ayon_server/graphql/utils.py
  ayon_server/helpers/inherited_attributes.py
  ayon_server/types.py
  setup/__main__.py
  setup/attributes.py
Labels: type: enhancement

#364 Optimize entity thumbnail storage
  api/thumbnails/thumbnails.py
  ayon_server/background/clean_up.py
  ayon_server/files/project_storage.py
  ayon_server/files/s3.py
  ayon_server/helpers/thumbnails.py
  schemas/schema.project.sql
  schemas/schema.public.update.sql
Labels: type: enhancement
