Repository ynput/ayon-backend, pull requests merged in 2025-02, with the labels that each got.

#498 Inbox: API enhancements
  api/inbox/inbox.py
Labels: type: enhancement

#507 REST: tasksFolders endpoint
  api/events/enroll.py
  api/events/operations.py
  api/query/query.py
  api/tasks_folders/__init__.py
  api/tasks_folders/tasks_folders.py
  ayon_server/events/enroll.py
  ayon_server/graphql/resolvers/tasks.py
  ayon_server/sqlfilter.py
Labels: type: feature

#501 Activities: Activity tags API
  api/activities/activity.py
  ayon_server/activities/create_activity.py
  ayon_server/activities/update_activity.py
  ayon_server/graphql/nodes/activity.py
  ayon_server/graphql/resolvers/activities.py
  schemas/migrations/00000001.sql
  schemas/migrations/00000002.sql
  schemas/migrations/00000005.sql
  schemas/schema.project.sql
  schemas/schema.public.sql
Labels: type: feature

#509 Switch to marketplace api v2
  api/bundles/models.py
  api/market/addons.py
  api/market/common.py
  api/market/licenses.py
  api/market/models.py
  api/market/releases.py
  ayon_server/events/base.py
  ayon_server/installer/models.py
  ayon_server/models/__init__.py
  ayon_server/models/rest_model.py
  ayon_server/types.py
  ayon_server/utils.py
Labels: type: maintenance

#511 API: Routers defined by addons
  ayon_server/addons/addon.py
  ayon_server/api/dependencies.py
  ayon_server/api/server.py
Labels: type: feature

#515 Disallow guest users creating guest admins and guest services
  api/users/users.py
Labels: type: bug

#516 Inbox: do not consider status changes as important for notifications
  ayon_server/activities/create_activity.py
Labels: type: bug

#519 Files: Allow uploading project files from the server, addons and remote sources
  api/files/files.py
  api/review/listing.py
  api/review/upload.py
  api/review/utils.py
  ayon_server/files/__init__.py
  ayon_server/files/project_file_record.py
  ayon_server/files/project_storage.py
  ayon_server/files/s3.py
  ayon_server/helpers/download.py
  ayon_server/models/file_info.py
  ayon_server/reviewables/__init__.py
  ayon_server/reviewables/create_reviewable.py
  ayon_server/reviewables/models.py
  tests/test_ayon_server_utils.py
Labels: type: feature

#517 Relabel `motd` customization "Message of the Day" to "Login Page Message"
  api/system/info.py
  ayon_server/config/serverconfig.py
Labels: type: enhancement
