Repository ynput/ayon-backend, pull requests merged in 2025-04, with the labels that each got.

#557 Improved performance of the most used endpoints
  api/bundles/bundles.py
  api/projects/anatomy.py
  api/settings/models.py
  api/settings/settings.py
  api/settings/settings_addons_list.py
  ayon_server/addons/addon.py
  ayon_server/addons/settings_caching.py
  ayon_server/info.py
  ayon_server/lib/postgres.py
  ayon_server/utils/__init__.py
  ayon_server/utils/request_coalescer.py
Labels: type: enhancement

#558 New enum for anatomy templates
  ayon_server/settings/__init__.py
  ayon_server/settings/enum.py
  ayon_server/settings/postprocess.py
Labels: type: enhancement

#565 Handle pydantic validation error in project level operations
  ayon_server/operations/project_level/__init__.py
  ayon_server/settings/__init__.py
  ayon_server/settings/enum.py
Labels: type: bug

#567 Respect attribute whitelist in folder_list endpoint
  api/folders/list_folders.py
  ayon_server/access/access_groups.py
  ayon_server/access/permissions.py
Labels: type: bug

#569 Chore: Templates enum
  ayon_server/settings/enum.py
Labels: type: enhancement

#570 Use attribute whitelist for entity updates
  ayon_server/entities/core/base.py
  ayon_server/events/patch.py
  ayon_server/operations/project_level/entity_update.py
Labels: type: bug

#566 Propagate changes to project aux tables to event stream
  ayon_server/events/patch.py
Labels: type: bug

#568 Streamlined array comparison in SQLFilter
  ayon_server/sqlfilter.py
Labels: type: bug

#573 Polished service configuration updates
  api/services/hosts.py
  api/services/services.py
Labels: type: enhancement

#562 New version status respects filtering by Scope
  ayon_server/entities/core/projectlevel.py
  ayon_server/helpers/statuses.py
Labels: type: bug

#563 Actions configuration, interactive actions, grouping and project-level actions.
  api/actions/actions.py
  api/actions/listing.py
  ayon_server/actions/config.py
  ayon_server/actions/context.py
  ayon_server/actions/execute.py
  ayon_server/actions/manifest.py
  ayon_server/addons/addon.py
  ayon_server/api/lifespan.py
  ayon_server/forms/__init__.py
  ayon_server/forms/simple_form.py
  maintenance/tasks/__init__.py
  maintenance/tasks/remove_old_action_configs.py
  schemas/schema.public.sql
Labels: type: feature

#576 Propagate user to settings.changed events
  api/addons/common.py
  api/addons/project_settings.py
  api/addons/studio_settings.py
  api/settings/settings.py
Labels: type: bug

#482 Entity lists
  api/addons/configuration.py
  api/addons/delete_addon.py
  api/addons/install.py
  api/addons/list_addons.py
  api/addons/project_settings.py
  api/addons/router.py
  api/addons/site_settings.py
  api/addons/studio_settings.py
  api/config/router.py
  api/entity_lists/__init__.py
  api/entity_lists/entities.py
  api/entity_lists/list_items.py
  api/entity_lists/lists.py
  api/entity_lists/router.py
  api/files/router.py
  api/inbox/router.py
  api/market/router.py
  api/onboarding/router.py
  api/operations/router.py
  api/services/hosts.py
  api/services/router.py
  api/services/services.py
  api/settings/router.py
  api/system/__init__.py
  api/system/frontend_modules.py
  api/system/info.py
  api/system/metrics.py
  api/system/router.py
  api/system/secrets.py
  api/system/sites.py
  api/ynputcloud/__init__.py
  api/ynputcloud/connect.py
  api/ynputcloud/feedback.py
  api/ynputcloud/router.py
  ayon_server/addons/definition.py
  ayon_server/api/metadata.py
  ayon_server/api/server.py
  ayon_server/config/ayonconfig.py
  ayon_server/entity_lists/__init__.py
  ayon_server/entity_lists/entity_folder_path.py
  ayon_server/entity_lists/entity_list.py
  ayon_server/entity_lists/load_entity_list.py
  ayon_server/entity_lists/models.py
  ayon_server/entity_lists/save_entity_list.py
  ayon_server/graphql/__init__.py
  ayon_server/graphql/connections.py
  ayon_server/graphql/dataloaders/__init__.py
  ayon_server/graphql/edges.py
  ayon_server/graphql/nodes/entity_list.py
  ayon_server/graphql/nodes/project.py
  ayon_server/graphql/resolvers/common.py
  ayon_server/graphql/resolvers/entity_list_items.py
  ayon_server/graphql/resolvers/entity_lists.py
  ayon_server/graphql/resolvers/tasks.py
  ayon_server/utils/__init__.py
  ayon_server/utils/utils.py
  schemas/migrations/00000006.sql
  schemas/schema.project.sql
Labels: epic, type: feature

#582 New logging middleware
  api/addons/router.py
  api/thumbnails/thumbnails.py
  api/users/router.py
  ayon_server/api/auth.py
  ayon_server/api/logging.py
  ayon_server/api/responses.py
  ayon_server/api/server.py
  ayon_server/api/system.py
  ayon_server/logging.py
  ayon_server/utils/strings.py
Labels: type: enhancement

#583 Custom attributes for entity list items
  api/attributes/attributes.py
  api/attributes/models.py
  api/entity_lists/__init__.py
  api/entity_lists/attributes.py
  ayon_server/attributes/models.py
  ayon_server/attributes/validate_attribute_data.py
  ayon_server/graphql/__init__.py
  ayon_server/graphql/nodes/entity_list.py
  ayon_server/graphql/nodes/folder.py
  ayon_server/graphql/nodes/product.py
  ayon_server/graphql/nodes/project.py
  ayon_server/graphql/nodes/representation.py
  ayon_server/graphql/nodes/task.py
  ayon_server/graphql/nodes/user.py
  ayon_server/graphql/nodes/version.py
  ayon_server/graphql/nodes/workfile.py
  ayon_server/graphql/utils.py
Labels: type: feature
