Repository ynput/ayon-backend, pull requests merged in 2025-01, with the labels that each got.

#477 Added task type colors
  ayon_server/settings/anatomy/task_types.py
Labels: type: enhancement

#310 Events: Reusable events
  api/addons/install.py
  api/events/events.py
  ayon_server/api/system.py
  ayon_server/events/__init__.py
  ayon_server/events/eventstream.py
Labels: type: enhancement

#451 Exclude demo and testing projects from metrics
  ayon_server/helpers/deploy_project.py
  ayon_server/helpers/project_list.py
  ayon_server/metrics/projects.py
  demogen/__main__.py
Labels: type: enhancement

#474 User activity monitoring
  ayon_server/auth/session.py
  ayon_server/metrics/__init__.py
  ayon_server/metrics/traffic.py
  ayon_server/metrics/users.py
  maintenance/tasks/push_metrics.py
  schemas/schema.public.sql
Labels: type: enhancement

#480 Settings: Migrate settings with no overrides
  ayon_server/addons/addon.py
Labels: type: enhancement

#481 Projects: Optional flag to disable auto-assigning users to new projects
  api/projects/deploy.py
  ayon_server/helpers/deploy_project.py
Labels: type: enhancement

#488 Addons: Allow returning frontend scopes and frontend modules conditionally
  api/addons/list_addons.py
  api/system/frontend_modules.py
  ayon_server/addons/addon.py
Labels: type: enhancement

#490 Email handling improvements
  api/users/password_reset.py
  ayon_server/entities/user.py
Labels: type: bug

#493 Server API for thumbnail uploads
  api/thumbnails/thumbnails.py
  ayon_server/helpers/thumbnails.py
Labels: type: enhancement

#495 Events: Horizontal scaling support in EventStream.subscribe
  ayon_server/addons/library.py
  ayon_server/api/messaging.py
  ayon_server/events/eventstream.py
Labels: type: feature

#499 License change from Apache 2.0 to FSL-1.1-ALv2
  LICENSE
Labels: type: maintenance, bump minor

#500 Watchers: unset watcher when assignment is removed
  ayon_server/activities/event_hook.py
  ayon_server/activities/watchers/set_watchers.py
Labels: type: bug

#504 Setup: Optimized migration scripts
  schemas/migrations/00000001.sql
  schemas/migrations/00000002.sql
  schemas/migrations/00000003.sql
  schemas/migrations/00000004.sql
  setup/__main__.py
Labels: type: enhancement
