Repository ynput/ayon-backend, pull requests merged in 2025-07, with the labels that each got.

#646 Improve settings loading concurrency
  api/settings/settings.py
  ayon_server/addons/addon.py
  ayon_server/api/messaging.py
  ayon_server/events/__init__.py
  ayon_server/events/base.py
  ayon_server/events/default_hooks.py
  ayon_server/events/eventstream.py
  ayon_server/initialize.py
  ayon_server/operations/project_level/__init__.py
  ayon_server/utils/request_coalescer.py
Labels: type: enhancement

#647 Project level operations: Improved entity updating and events dispatching
  api/activities/activity.py
  api/operations/operations.py
  ayon_server/activities/create_activity.py
  ayon_server/entities/version.py
  ayon_server/operations/project_level/__init__.py
  ayon_server/operations/project_level/entity_create.py
  ayon_server/operations/project_level/entity_delete.py
  ayon_server/operations/project_level/entity_update.py
  ayon_server/reviewables/create_reviewable.py
Labels: type: bug

#656 GraphQL: fuzzy search argument to all entities
  ayon_server/graphql/resolvers/folders.py
  ayon_server/graphql/resolvers/products.py
  ayon_server/graphql/resolvers/representations.py
  ayon_server/graphql/resolvers/versions.py
  ayon_server/graphql/resolvers/workfiles.py
Labels: type: feature

#659 Actions: List actions endpoint allows to specify settings variant
  api/actions/actions.py
  api/actions/listing.py
Labels: type: enhancement

#661 GraphQL: expose parents (and path) fields on all project level entity nodes
  ayon_server/graphql/__init__.py
  ayon_server/graphql/dataloaders/__init__.py
  ayon_server/graphql/nodes/common.py
  ayon_server/graphql/nodes/folder.py
  ayon_server/graphql/nodes/product.py
  ayon_server/graphql/nodes/representation.py
  ayon_server/graphql/nodes/task.py
  ayon_server/graphql/nodes/version.py
  ayon_server/graphql/nodes/workfile.py
  ayon_server/graphql/resolvers/products.py
  ayon_server/graphql/resolvers/representations.py
  ayon_server/graphql/resolvers/tasks.py
  ayon_server/graphql/resolvers/versions.py
  ayon_server/graphql/resolvers/workfiles.py
Labels: type: enhancement

#663 Support for parents/path for list items entities
  ayon_server/graphql/resolvers/entity_list_items.py
Labels: type: enhancement

#665 Shell: dbshell tool
  dbshell
Labels: type: enhancement
