Repository ynput/ayon-backend, pull requests merged in 2025-03, with the labels that each got.

#523 API: Unified authentication and logging middleware
  api/events/enroll.py
  api/services/hosts.py
  api/system/info.py
  ayon_server/activities/create_activity.py
  ayon_server/api/__init__.py
  ayon_server/api/authmw.py
  ayon_server/api/dependencies.py
  ayon_server/api/lifespan.py
  ayon_server/api/messaging.py
  ayon_server/api/server.py
  ayon_server/background/log_collector.py
  ayon_server/config/ayonconfig.py
  ayon_server/events/eventstream.py
  ayon_server/helpers/hierarchy_cache.py
  ayon_server/helpers/inherited_attributes.py
  ayon_server/logging.py
  ayon_server/operations/project_level.py
  ayon_server/utils/strings.py
Labels: type: enhancement

#526 Events: emit granular events when project is updated
  api/projects/anatomy.py
  api/projects/projects.py
  ayon_server/events/patch.py
Labels: type: enhancement

#527 REST: Use ProjectLevelOperations in create-update-delete endpoints
  api/folders/folders.py
  api/products/products.py
  api/representations/representations.py
  api/tasks/tasks.py
  api/versions/versions.py
  api/workfiles/workfiles.py
  ayon_server/operations/common.py
  ayon_server/operations/project_level/__init__.py
  ayon_server/operations/project_level/entity_create.py
  ayon_server/operations/project_level/entity_delete.py
  ayon_server/operations/project_level/entity_update.py
  ayon_server/operations/project_level/models.py
Labels: type: enhancement

#531 GraphQL: New pagination, filtering and sorting by inherited attributes and allAttrib field
  api/tasks_folders/tasks_folders.py
  ayon_server/graphql/__init__.py
  ayon_server/graphql/nodes/folder.py
  ayon_server/graphql/nodes/product.py
  ayon_server/graphql/nodes/project.py
  ayon_server/graphql/nodes/representation.py
  ayon_server/graphql/nodes/task.py
  ayon_server/graphql/nodes/user.py
  ayon_server/graphql/nodes/version.py
  ayon_server/graphql/nodes/workfile.py
  ayon_server/graphql/resolvers/activities.py
  ayon_server/graphql/resolvers/common.py
  ayon_server/graphql/resolvers/events.py
  ayon_server/graphql/resolvers/folders.py
  ayon_server/graphql/resolvers/inbox.py
  ayon_server/graphql/resolvers/kanban.py
  ayon_server/graphql/resolvers/pagination.py
  ayon_server/graphql/resolvers/products.py
  ayon_server/graphql/resolvers/projects.py
  ayon_server/graphql/resolvers/representations.py
  ayon_server/graphql/resolvers/tasks.py
  ayon_server/graphql/resolvers/users.py
  ayon_server/graphql/resolvers/versions.py
  ayon_server/graphql/resolvers/workfiles.py
  ayon_server/graphql/utils.py
  ayon_server/sqlfilter.py
  ayon_server/utils/sqltool.py
Labels: type: feature

#535 Provide error messages in 401 responses
  api/users/users.py
  ayon_server/api/authmw.py
  ayon_server/auth/session.py
  ayon_server/helpers/rename_user.py
Labels: type: enhancement

#538 Filter users by emails in GraphQL
  ayon_server/graphql/resolvers/users.py
  ayon_server/types.py
Labels: type: enhancement

#536 Add validator to attribute data model
  api/attributes/attributes.py
  api/attributes/models.py
  api/attributes/validator.py
  ayon_server/entities/models/generator.py
Labels: type: bug

#529 Inbox: Truncate message body
  ayon_server/graphql/nodes/activity.py
  ayon_server/graphql/resolvers/inbox.py
  schemas/schema.public.sql
Labels: type: enhancement

#528 Core: Use strict type for anatomy related project fields
  api/projects/anatomy.py
  api/projects/projects.py
  ayon_server/entities/core/projectlevel.py
  ayon_server/entities/project.py
  ayon_server/entities/project_aux_tables.py
  ayon_server/helpers/extract_anatomy.py
  ayon_server/helpers/get_entity_class.py
  ayon_server/settings/anatomy/__init__.py
  ayon_server/settings/anatomy/aux_model.py
  ayon_server/settings/anatomy/folder_types.py
  ayon_server/settings/anatomy/statuses.py
  ayon_server/settings/anatomy/tags.py
  ayon_server/settings/anatomy/task_types.py
Labels: type: enhancement

#544 REST: Add text search support to /taskFolders endpoint
  api/tasks_folders/tasks_folders.py
Labels: type: feature

#546 Comments: Allow normal users to check checkboxes on comments with attachments
  ayon_server/activities/update_activity.py
Labels: type: bug

#550 Performance improvements
  api/connect/__init__.py
  api/folders/folders.py
  api/folders/list_folders.py
  api/onboarding/onboarding.py
  api/system/info.py
  api/users/avatar.py
  ayon_server/api/authmw.py
  ayon_server/api/lifespan.py
  ayon_server/api/server.py
  ayon_server/graphql/resolvers/tasks.py
  ayon_server/helpers/cloud.py
  ayon_server/helpers/download.py
  ayon_server/helpers/hierarchy_cache.py
  ayon_server/helpers/preview.py
  ayon_server/helpers/project_list.py
  ayon_server/helpers/setup.py
  linker/linker.py
  nxtools/__init__.py
Labels: type: enhancement

#553 Improved folder list concurency
  api/folders/list_folders.py
Labels: type: enhancement

#552 Add representation traits to graphql
  ayon_server/graphql/nodes/representation.py
  ayon_server/graphql/resolvers/representations.py
Labels: type: enhancement

#521 Backend support for project bundles
  api/addons/list_addons.py
  api/bundles/bundles.py
  api/bundles/models.py
  api/projects/__init__.py
  api/projects/bundle.py
  api/settings/settings.py
  ayon_server/addons/addon.py
  ayon_server/addons/definition.py
  ayon_server/graphql/nodes/project.py
  ayon_server/graphql/resolvers/projects.py
Labels: type: feature

#555 Support for ACL with horizontal scaling
  api/access/access_groups.py
  api/folders/list_folders.py
  api/tasks_folders/tasks_folders.py
  ayon_server/access/access_groups.py
  ayon_server/access/utils.py
  ayon_server/api/lifespan.py
Labels: type: feature
